#pragma once

#define IDR_PANEL_ICON_CPU 101
#define IDR_PANEL_ICON_GPU 102
#define IDR_PANEL_ICON_NETWORK 103
#define IDR_PANEL_ICON_STORAGE 104
#define IDR_PANEL_ICON_TIME 105
#define IDI_APP_ICON 201
