#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

struct ParseResult {
    bool ok = false;
    std::string error;
};

enum class SyntaxNodeKind : std::uint8_t {
    Tree,
    KnownToken,
    FreeToken,
    Comment,
    TrailingComment,
    BlankLine,
};

enum class SyntaxTreeKind : std::uint16_t {
    Unknown,
    TranslationUnit,
    IncludeRun,
    MacroReplacementList,
    Declaration,
    FieldDeclaration,
    AliasDeclaration,
    FunctionDefinition,
    CompoundStatement,
    FieldDeclarationList,
    EnumeratorList,
    InitializerList,
    FieldInitializerList,
    FieldInitializer,
    DeclarationList,
    NamespaceDefinition,
    EnumSpecifier,
    ClassSpecifier,
    StructSpecifier,
    IfStatement,
    ElseClause,
    ForStatement,
    WhileStatement,
    DoStatement,
    SwitchStatement,
    CaseStatement,
    ConditionClause,
    InitStatement,
    PreprocCall,
    PreprocDef,
    PreprocFunctionDef,
    PreprocInclude,
    PreprocIf,
    PreprocIfdef,
    PreprocElse,
    PreprocElif,
    PreprocUsing,
    PreprocParams,
    PreprocArg,
    BinaryExpression,
    UnaryExpression,
    ConditionalExpression,
    CommaExpression,
    AssignmentExpression,
    InitDeclarator,
    CastExpression,
    PointerDeclarator,
    AbstractPointerDeclarator,
    ReferenceDeclarator,
    AbstractReferenceDeclarator,
    HandleDeclarator,
    AbstractHandleDeclarator,
    MemberPointerDeclarator,
    FunctionDeclarator,
    AbstractFunctionDeclarator,
    ParenthesizedDeclarator,
    AbstractParenthesizedDeclarator,
    ParameterList,
    ArgumentList,
    TemplateParameterList,
    TemplateArgumentList,
    TemplateDeclaration,
    RequiresClause,
    LambdaExpression,
    LambdaCaptureSpecifier,
    StructuredBindingDeclarator,
    FieldDesignator,
    FieldExpression,
    TrailingReturnType,
    OperatorName,
    OperatorCast,
    MsCallModifier,
    MsDeclspecModifier,
    ConcatenatedString,
    RawStringLiteral,
    StringLiteral,
    SystemLibString,
    CharacterLiteral,
    NumberLiteral,
    Identifier,
};

enum class KnownToken : std::uint16_t {
    Unknown,
    Hash,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    EqualEqual,
    BangEqual,
    Spaceship,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Ampersand,
    Pipe,
    Bang,
    Tilde,
    Equal,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    CaretEqual,
    AmpersandEqual,
    PipeEqual,
    LessLess,
    GreaterGreater,
    LessLessEqual,
    GreaterGreaterEqual,
    AmpersandAmpersand,
    PipePipe,
    PlusPlus,
    MinusMinus,
    Arrow,
    Dot,
    ArrowStar,
    DotStar,
    ColonColon,
    Question,
    Colon,
    Semicolon,
    Comma,
    Ellipsis,
    KeywordAlignas,
    KeywordAlignof,
    KeywordAsm,
    KeywordAuto,
    KeywordBool,
    KeywordBreak,
    KeywordCase,
    KeywordCatch,
    KeywordChar,
    KeywordChar16T,
    KeywordChar32T,
    KeywordClass,
    KeywordConcept,
    KeywordConst,
    KeywordConsteval,
    KeywordConstexpr,
    KeywordConstinit,
    KeywordConstCast,
    KeywordContinue,
    KeywordDecltype,
    KeywordDefault,
    KeywordDelete,
    KeywordDo,
    KeywordDouble,
    KeywordDynamicCast,
    KeywordElse,
    KeywordEnum,
    KeywordExplicit,
    KeywordExport,
    KeywordExtern,
    KeywordFalse,
    KeywordFinal,
    KeywordFinally,
    KeywordFloat,
    KeywordFor,
    KeywordFriend,
    KeywordGoto,
    KeywordIf,
    KeywordInline,
    KeywordInt,
    KeywordLong,
    KeywordMutable,
    KeywordNamespace,
    KeywordNew,
    KeywordNoexcept,
    KeywordNullptr,
    KeywordOperator,
    KeywordOverride,
    KeywordPrivate,
    KeywordProtected,
    KeywordPublic,
    KeywordRegister,
    KeywordReinterpretCast,
    KeywordRequires,
    KeywordReturn,
    KeywordShort,
    KeywordSigned,
    KeywordSizeof,
    KeywordStatic,
    KeywordStaticAssert,
    KeywordStaticCast,
    KeywordStruct,
    KeywordSwitch,
    KeywordTemplate,
    KeywordThis,
    KeywordThreadLocal,
    KeywordThrow,
    KeywordTrue,
    KeywordTry,
    KeywordTypedef,
    KeywordTypeid,
    KeywordTypename,
    KeywordUnion,
    KeywordUnsigned,
    KeywordUsing,
    KeywordVirtual,
    KeywordVoid,
    KeywordVolatile,
    KeywordWcharT,
    KeywordWhile,
    KeywordCdecl,
    KeywordDeclspec,
    KeywordCoAwait,
    KeywordCoReturn,
    KeywordCoYield,
};

enum class TokenClass : std::uint32_t {
    Keyword = 1u << 0,
    ControlKeyword = 1u << 1,
    AttachAfterBlockKeyword = 1u << 2,
    AccessKeyword = 1u << 3,
    MemberOperator = 1u << 4,
    AssignmentOperator = 1u << 5,
    BinaryOperator = 1u << 6,
    UnaryOperator = 1u << 7,
    DeclaratorReferenceToken = 1u << 8,
};

KnownToken KnownTokenFromText(std::string_view text);
std::string_view KnownTokenText(KnownToken token);
bool KnownTokenHasClass(KnownToken token, TokenClass tokenClass);

struct SyntaxNode {
    // Keep nodes maximally generic and space-efficient; avoid fields that only apply to one node kind.
    SyntaxNodeKind kind = SyntaxNodeKind::Tree;
    SyntaxTreeKind treeKind = SyntaxTreeKind::Unknown;
    KnownToken known = KnownToken::Unknown;
    std::string_view text;
    std::vector<std::unique_ptr<SyntaxNode>> children;
};

struct FormatModel {
    FormatModel() = default;
    FormatModel(const FormatModel&) = delete;
    FormatModel& operator=(const FormatModel&) = delete;
    FormatModel(FormatModel&&) noexcept = default;
    FormatModel& operator=(FormatModel&&) noexcept = default;

    ParseResult parse;
    std::unique_ptr<std::string> sourceText;
    std::unique_ptr<SyntaxNode> root;
};
